SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
TITLE = "Echoes Beyond the Moon"

# Scenes
SCENE_MENU = "menu"
SCENE_PROLOGUE = "prologue"
SCENE_LEVEL1 = "level1"
SCENE_LEVEL2 = "level2"
SCENE_GAMEOVER = "gameover"

# Player
MAX_LIVES = 3

# Level 1
OXYGEN_MAX = 100
OXYGEN_DRAIN_RATE = 0.02
OXYGEN_DRAIN_RUN = 0.01
OXYGEN_DRAIN_JUMP = 0.05
OXYGEN_TANK_REFILL = 30
GRAVITY = 0.3
JUMP_FORCE = -12
